// Catalog of amCharts 5 geodata maps available from the official CDN
// (https://cdn.amcharts.com/lib/5/geodata/<id>.js — each sets
// window.am5geodata_<id>). Generated from the amcharts_geodata 5.1.5 file
// listing: every top-level *Low.js map, labeled for the builder's region
// dropdown. "World" is pinned first; the rest are alphabetical.
export const MAP_REGIONS = [
  { id: "worldLow", label: "World" },
  { id: "afghanistanLow", label: "Afghanistan" },
  { id: "albaniaLow", label: "Albania" },
  { id: "algeriaLow", label: "Algeria" },
  { id: "americanSamoaLow", label: "American Samoa" },
  { id: "andorraLow", label: "Andorra" },
  { id: "angolaLow", label: "Angola" },
  { id: "anguillaLow", label: "Anguilla" },
  { id: "antiguaBarbudaLow", label: "Antigua & Barbuda" },
  { id: "argentinaLow", label: "Argentina" },
  { id: "armeniaLow", label: "Armenia" },
  { id: "arubaLow", label: "Aruba" },
  { id: "australiaLow", label: "Australia" },
  { id: "austriaLow", label: "Austria" },
  { id: "azerbaijanLow", label: "Azerbaijan" },
  { id: "bahamasLow", label: "Bahamas" },
  { id: "bahrainLow", label: "Bahrain" },
  { id: "bangladeshLow", label: "Bangladesh" },
  { id: "barbadosLow", label: "Barbados" },
  { id: "belarusLow", label: "Belarus" },
  { id: "belgiumLow", label: "Belgium" },
  { id: "belizeLow", label: "Belize" },
  { id: "beninLow", label: "Benin" },
  { id: "bermudaLow", label: "Bermuda" },
  { id: "bhutanLow", label: "Bhutan" },
  { id: "boliviaLow", label: "Bolivia" },
  { id: "bonaireSintEustatiusSabaLow", label: "Bonaire, Sint Eustatius & Saba" },
  { id: "bosniaHerzegovinaLow", label: "Bosnia & Herzegovina" },
  { id: "bosniaHerzegovinaCantonsLow", label: "Bosnia Herzegovina Cantons" },
  { id: "botswanaLow", label: "Botswana" },
  { id: "brazilLow", label: "Brazil" },
  { id: "britishIndianOceanTerritoryLow", label: "British Indian Ocean Territory" },
  { id: "britishVirginIslandsLow", label: "British Virgin Islands" },
  { id: "bruneiDarussalamLow", label: "Brunei Darussalam" },
  { id: "bulgariaLow", label: "Bulgaria" },
  { id: "burkinaFasoLow", label: "Burkina Faso" },
  { id: "burundiLow", label: "Burundi" },
  { id: "cambodiaLow", label: "Cambodia" },
  { id: "cameroonLow", label: "Cameroon" },
  { id: "canadaLow", label: "Canada" },
  { id: "capeVerdeLow", label: "Cape Verde" },
  { id: "caymanIslandsLow", label: "Cayman Islands" },
  { id: "centralAfricanRepublicLow", label: "Central African Republic" },
  { id: "chadLow", label: "Chad" },
  { id: "channelIslandsLow", label: "Channel Islands" },
  { id: "chileLow", label: "Chile" },
  { id: "chinaLow", label: "China" },
  { id: "cocosKeelingLow", label: "Cocos Keeling" },
  { id: "colombiaLow", label: "Colombia" },
  { id: "colombiaMuniLow", label: "Colombia Muni" },
  { id: "comorosLow", label: "Comoros" },
  { id: "continentsLow", label: "Continents" },
  { id: "continentsRussiaAsiaLow", label: "Continents (Russia in Asia)" },
  { id: "continentsRussiaEuropeLow", label: "Continents (Russia in Europe)" },
  { id: "costaRicaLow", label: "Costa Rica" },
  { id: "cotedIvoireLow", label: "Coted Ivoire" },
  { id: "croatiaLow", label: "Croatia" },
  { id: "cubaLow", label: "Cuba" },
  { id: "curacaoLow", label: "Curacao" },
  { id: "cyprusLow", label: "Cyprus" },
  { id: "cyprusNorthCyprusLow", label: "Cyprus (with North Cyprus)" },
  { id: "czechRepublicLow", label: "Czech Republic (regions)" },
  { id: "czechiaLow", label: "Czechia" },
  { id: "denmarkLow", label: "Denmark" },
  { id: "djiboutiLow", label: "Djibouti" },
  { id: "dominicaLow", label: "Dominica" },
  { id: "dominicanRepublicLow", label: "Dominican Republic" },
  { id: "dominicanRepublicMuniLow", label: "Dominican Republic Muni" },
  { id: "congoDRLow", label: "DR Congo" },
  { id: "ecuadorLow", label: "Ecuador" },
  { id: "egyptLow", label: "Egypt" },
  { id: "elSalvadorLow", label: "El Salvador" },
  { id: "equatorialGuineaLow", label: "Equatorial Guinea" },
  { id: "eritreaLow", label: "Eritrea" },
  { id: "estoniaLow", label: "Estonia" },
  { id: "eswatiniLow", label: "Eswatini" },
  { id: "ethiopiaLow", label: "Ethiopia" },
  { id: "falklandIslandsLow", label: "Falkland Islands" },
  { id: "faroeIslandsLow", label: "Faroe Islands" },
  { id: "fijiEastLow", label: "Fiji East" },
  { id: "fijiWestLow", label: "Fiji West" },
  { id: "finlandLow", label: "Finland" },
  { id: "franceLow", label: "France" },
  { id: "franceDepartmentsLow", label: "France Departments" },
  { id: "franceDepartments2Low", label: "France Departments2" },
  { id: "frenchGuianaLow", label: "French Guiana" },
  { id: "frenchPolynesiaLow", label: "French Polynesia" },
  { id: "gabonLow", label: "Gabon" },
  { id: "gambiaLow", label: "Gambia" },
  { id: "georgiaLow", label: "Georgia" },
  { id: "georgiaSouthOssetiaLow", label: "Georgia South Ossetia" },
  { id: "germanyLow", label: "Germany" },
  { id: "ghanaLow", label: "Ghana" },
  { id: "greeceLow", label: "Greece" },
  { id: "greenlandLow", label: "Greenland" },
  { id: "grenadaLow", label: "Grenada" },
  { id: "guadeloupeLow", label: "Guadeloupe" },
  { id: "guamLow", label: "Guam" },
  { id: "guatemalaLow", label: "Guatemala" },
  { id: "guineaLow", label: "Guinea" },
  { id: "guineaBissauLow", label: "Guinea Bissau" },
  { id: "guyanaLow", label: "Guyana" },
  { id: "haitiLow", label: "Haiti" },
  { id: "hondurasLow", label: "Honduras" },
  { id: "hongKongLow", label: "Hong Kong" },
  { id: "hungaryLow", label: "Hungary" },
  { id: "icelandLow", label: "Iceland" },
  { id: "indiaLow", label: "India" },
  { id: "india2019Low", label: "India2019" },
  { id: "india2020Low", label: "India2020" },
  { id: "india2023Low", label: "India2023" },
  { id: "indonesiaLow", label: "Indonesia" },
  { id: "iranLow", label: "Iran" },
  { id: "iraqLow", label: "Iraq" },
  { id: "irelandLow", label: "Ireland" },
  { id: "irelandProvincesLow", label: "Ireland Provinces" },
  { id: "israelLow", label: "Israel" },
  { id: "israelPalestineLow", label: "Israel Palestine" },
  { id: "italyLow", label: "Italy" },
  { id: "italyProvincesLow", label: "Italy Provinces" },
  { id: "jamaicaLow", label: "Jamaica" },
  { id: "japanLow", label: "Japan" },
  { id: "jordanLow", label: "Jordan" },
  { id: "kazakhstanLow", label: "Kazakhstan" },
  { id: "kazakhstan2023Low", label: "Kazakhstan2023" },
  { id: "kenyaLow", label: "Kenya" },
  { id: "kosovoLow", label: "Kosovo" },
  { id: "kuwaitLow", label: "Kuwait" },
  { id: "kyrgyzstanLow", label: "Kyrgyzstan" },
  { id: "laosLow", label: "Laos" },
  { id: "latviaLow", label: "Latvia" },
  { id: "latvia2021Low", label: "Latvia2021" },
  { id: "lebanonLow", label: "Lebanon" },
  { id: "lesothoLow", label: "Lesotho" },
  { id: "liberiaLow", label: "Liberia" },
  { id: "libyaLow", label: "Libya" },
  { id: "liechtensteinLow", label: "Liechtenstein" },
  { id: "lithuaniaLow", label: "Lithuania" },
  { id: "luxembourgLow", label: "Luxembourg" },
  { id: "madagascarProvinceLow", label: "Madagascar Province" },
  { id: "madagascarRegionLow", label: "Madagascar Region" },
  { id: "malawiLow", label: "Malawi" },
  { id: "malaysiaLow", label: "Malaysia" },
  { id: "maldivesLow", label: "Maldives" },
  { id: "maldivesIslandsLow", label: "Maldives Islands" },
  { id: "maliLow", label: "Mali" },
  { id: "maltaLow", label: "Malta" },
  { id: "martiniqueLow", label: "Martinique" },
  { id: "mauritaniaLow", label: "Mauritania" },
  { id: "mauritiusLow", label: "Mauritius" },
  { id: "mexicoLow", label: "Mexico" },
  { id: "moldovaLow", label: "Moldova" },
  { id: "mongoliaLow", label: "Mongolia" },
  { id: "montenegroLow", label: "Montenegro" },
  { id: "montserratLow", label: "Montserrat" },
  { id: "moroccoLow", label: "Morocco" },
  { id: "mozambiqueLow", label: "Mozambique" },
  { id: "myanmarLow", label: "Myanmar" },
  { id: "namibiaLow", label: "Namibia" },
  { id: "nepalLow", label: "Nepal" },
  { id: "nepal2020Low", label: "Nepal2020" },
  { id: "netherlandsLow", label: "Netherlands" },
  { id: "newZealandLow", label: "New Zealand" },
  { id: "nicaraguaLow", label: "Nicaragua" },
  { id: "nigerLow", label: "Niger" },
  { id: "nigeriaLow", label: "Nigeria" },
  { id: "northKoreaLow", label: "North Korea" },
  { id: "northMacedoniaLow", label: "North Macedonia" },
  { id: "northernMarianaLow", label: "Northern Mariana" },
  { id: "norwayLow", label: "Norway" },
  { id: "norway2020Low", label: "Norway2020" },
  { id: "omanLow", label: "Oman" },
  { id: "pakistanLow", label: "Pakistan" },
  { id: "palestineLow", label: "Palestine" },
  { id: "panamaLow", label: "Panama" },
  { id: "paraguayLow", label: "Paraguay" },
  { id: "peruLow", label: "Peru" },
  { id: "philippinesLow", label: "Philippines" },
  { id: "polandLow", label: "Poland" },
  { id: "portugalLow", label: "Portugal" },
  { id: "portugalRegionsLow", label: "Portugal Regions" },
  { id: "puertoRicoLow", label: "Puerto Rico" },
  { id: "qatarLow", label: "Qatar" },
  { id: "congoLow", label: "Republic of the Congo" },
  { id: "romaniaLow", label: "Romania" },
  { id: "russiaLow", label: "Russia" },
  { id: "russiaCrimeaLow", label: "Russia Crimea" },
  { id: "rwandaLow", label: "Rwanda" },
  { id: "saintHelenaLow", label: "Saint Helena" },
  { id: "saintLuciaLow", label: "Saint Lucia" },
  { id: "saintVincentLow", label: "Saint Vincent" },
  { id: "samoaLow", label: "Samoa" },
  { id: "sanMarinoLow", label: "San Marino" },
  { id: "saudiArabiaLow", label: "Saudi Arabia" },
  { id: "senegalLow", label: "Senegal" },
  { id: "serbiaLow", label: "Serbia" },
  { id: "serbiaNoKosovoLow", label: "Serbia No Kosovo" },
  { id: "seychellesLow", label: "Seychelles" },
  { id: "sierraLeoneLow", label: "Sierra Leone" },
  { id: "singaporeLow", label: "Singapore" },
  { id: "slovakiaLow", label: "Slovakia" },
  { id: "sloveniaLow", label: "Slovenia" },
  { id: "sloveniaRegionsLow", label: "Slovenia Regions" },
  { id: "solomonIslandsLow", label: "Solomon Islands" },
  { id: "somaliaLow", label: "Somalia" },
  { id: "southAfricaLow", label: "South Africa" },
  { id: "southKoreaLow", label: "South Korea" },
  { id: "southSudanLow", label: "South Sudan" },
  { id: "southSudan2015Low", label: "South Sudan2015" },
  { id: "spainLow", label: "Spain" },
  { id: "spainProvincesLow", label: "Spain Provinces" },
  { id: "spainProvinces2Low", label: "Spain Provinces2" },
  { id: "spain2Low", label: "Spain2" },
  { id: "sriLankaLow", label: "Sri Lanka" },
  { id: "stBarthelemyLow", label: "St Barthelemy" },
  { id: "stKittsNevisLow", label: "St. Kitts & Nevis" },
  { id: "stPierreMiquelonLow", label: "St. Pierre & Miquelon" },
  { id: "sudanLow", label: "Sudan" },
  { id: "surinameLow", label: "Suriname" },
  { id: "svalbardLow", label: "Svalbard" },
  { id: "swedenLow", label: "Sweden" },
  { id: "switzerlandLow", label: "Switzerland" },
  { id: "syriaLow", label: "Syria" },
  { id: "saoTomePrincipeLow", label: "São Tomé & Príncipe" },
  { id: "taiwanLow", label: "Taiwan" },
  { id: "tajikistanLow", label: "Tajikistan" },
  { id: "tanzaniaLow", label: "Tanzania" },
  { id: "thailandLow", label: "Thailand" },
  { id: "timorLesteLow", label: "Timor Leste" },
  { id: "togoLow", label: "Togo" },
  { id: "trinidadTobagoLow", label: "Trinidad & Tobago" },
  { id: "tunisiaLow", label: "Tunisia" },
  { id: "turkeyLow", label: "Turkey" },
  { id: "turkmenistanLow", label: "Turkmenistan" },
  { id: "turksCaicosLow", label: "Turks & Caicos" },
  { id: "ugandaLow", label: "Uganda" },
  { id: "ugandaRegionsLow", label: "Uganda Regions" },
  { id: "ukraineLow", label: "Ukraine" },
  { id: "unRegionsLow", label: "UN Regions" },
  { id: "uaeLow", label: "United Arab Emirates" },
  { id: "ukLow", label: "United Kingdom" },
  { id: "ukCountiesLow", label: "United Kingdom (counties)" },
  { id: "ukCountriesLow", label: "United Kingdom (countries)" },
  { id: "usaAlbersLow", label: "United States (Albers projection)" },
  { id: "usaLow", label: "United States (states)" },
  { id: "uruguayLow", label: "Uruguay" },
  { id: "usaTerritoriesLow", label: "US Territories" },
  { id: "usaTerritories2Low", label: "US Territories (detailed)" },
  { id: "usVirginIslandsLow", label: "US Virgin Islands" },
  { id: "uzbekistanLow", label: "Uzbekistan" },
  { id: "vaticanLow", label: "Vatican" },
  { id: "venezuelaLow", label: "Venezuela" },
  { id: "vietnamLow", label: "Vietnam" },
  { id: "worldChinaLow", label: "World (China POV)" },
  { id: "worldIndiaLow", label: "World (India POV)" },
  { id: "worldMoroccoLow", label: "World (Morocco POV)" },
  { id: "worldOutlineLow", label: "World (outline only)" },
  { id: "worldRussiaLow", label: "World (Russia POV)" },
  { id: "worldGreatLakesLow", label: "World (with Great Lakes)" },
  { id: "worldTimeZoneAreasLow", label: "World Time Zone Areas" },
  { id: "worldTimeZonesLow", label: "World Time Zones" },
  { id: "yemenLow", label: "Yemen" },
  { id: "zambiaLow", label: "Zambia" },
  { id: "zimbabweLow", label: "Zimbabwe" },
];
