/**
 * Guided build sequences for each model tab. Browser-safe ESM.
 */

export const THREE_STATEMENT_STEPS = [
  {
    id: 'revenue',
    pillLabel: 'Revenue',
    title: 'Forecast revenue',
    instruction: 'Set how fast sales grow each year. The income statement starts here — every later line builds on this top line.',
    whyOrder: 'You forecast sales first because costs, working capital, and cash flows all scale from revenue.',
    tableRows: 'Income statement → Revenue (and growth from the Sales growth assumption)',
    formula: 'Revenue = prior revenue × (1 + sales growth)',
    assumptionKeys: ['revenueGrowth'],
    rowKeys: ['revenue'],
    previewKey: 'revenue',
  },
  {
    id: 'margins',
    pillLabel: 'Costs & profit',
    title: 'Operating margins',
    instruction: 'Turn sales into gross profit and operating profit (EBIT). Margins come from the filing unless you override them.',
    whyOrder: 'After revenue, you need costs and profit before tax, interest, and cash effects.',
    tableRows: 'Income statement → Cost of sales, Gross profit, Operating expenses, EBIT, Taxes, Net income',
    formula: 'EBIT = revenue × operating margin',
    assumptionKeys: ['grossMargin', 'ebitMargin', 'taxRate'],
    rowKeys: ['cogs', 'grossProfit', 'opex', 'ebit', 'taxes', 'netIncome'],
    previewKey: 'ebit',
  },
  {
    id: 'working-capital',
    pillLabel: 'Working capital',
    title: 'Working capital',
    instruction: 'Size receivables and inventory from “days” assumptions. This is cash tied up in the business, not extra profit.',
    whyOrder: 'Working capital links the income statement to cash — longer days to collect means less cash even at the same profit.',
    tableRows: 'Balance sheet → Receivables, Inventory · Cash flow → working capital lines',
    formula: 'Receivables = revenue × DSO ÷ 365',
    assumptionKeys: ['dsoDays', 'dioDays'],
    rowKeys: ['receivables', 'inventory', 'cfo'],
    previewKey: 'receivables',
  },
  {
    id: 'capex-da',
    pillLabel: 'CapEx & depreciation',
    title: 'CapEx and depreciation',
    instruction: 'Capital spending is cash going out; depreciation is the non-cash expense spread over time.',
    whyOrder: 'CapEx hits cash flow immediately; depreciation hits profit over several years — both belong before the cash roll-forward.',
    tableRows: 'Cash flow → CapEx · Income statement → Depreciation · Balance sheet → PP&E',
    formula: 'CapEx = revenue × CapEx %; D&A = revenue × D&A %',
    assumptionKeys: ['capexPct', 'daPct'],
    rowKeys: ['capex', 'da', 'otherAssets'],
    previewKey: 'capex',
  },
  {
    id: 'financing',
    pillLabel: 'Debt & interest',
    title: 'Financing',
    instruction: 'Interest is charged on last year’s debt and cash — deliberately not circular. Debt paydown and dividends are cash out.',
    whyOrder: 'Financing sits after operations so interest uses known beginning balances, not this year’s plug.',
    tableRows: 'Income statement → Interest expense/income · Cash flow → Debt repayment, Dividends · Balance sheet → Debt',
    formula: 'Interest expense = beginning debt × rate',
    assumptionKeys: ['interestRate', 'debtRepaymentPct', 'payoutRatio'],
    rowKeys: ['interestExpense', 'interestIncome', 'debtRepayment', 'dividends', 'debt'],
    previewKey: 'interestExpense',
  },
  {
    id: 'cash-roll',
    pillLabel: 'Cash roll-forward',
    title: 'Cash and equity roll-forwards',
    instruction: 'Net income feeds equity; the cash flow statement’s net change becomes the cash balance (the plug).',
    whyOrder: 'The three statements must agree — cash and equity are where income statement and cash flow meet the balance sheet.',
    tableRows: 'Cash flow → Net change in cash · Balance sheet → Cash (plug), Shareholders’ equity',
    formula: 'Cash = prior cash + net change in cash (the plug)',
    assumptionKeys: [],
    rowKeys: ['netIncome', 'netChangeCash', 'cash', 'equity'],
    previewKey: 'cash',
  },
  {
    id: 'balance-check',
    pillLabel: 'Balance check',
    title: 'Balance check',
    instruction: 'Assets must equal liabilities plus equity every year. The check row should read zero before you trust the model.',
    whyOrder: 'This is the last step — proof that revenue, costs, cash, and financing all tie together.',
    tableRows: 'Balance sheet → Check row (should be zero)',
    formula: 'Check = total assets − total liabilities & equity',
    assumptionKeys: [],
    rowKeys: ['balanceCheck'],
    previewKey: 'balanceCheck',
  },
];

export const DCF_STEPS = [
  {
    id: 'fcf',
    pillLabel: 'Free cash flow',
    title: 'Forecast unlevered free cash flow',
    instruction: 'Pull unlevered FCF from the three-statement forecast.',
    whyOrder: 'DCF starts from cash the business generates, not accounting profit alone.',
    tableRows: 'DCF table → Unlevered free cash flow',
    formula: 'Unlevered FCF = EBIT × (1 − tax) + D&A − CapEx − Δ working capital',
    assumptionKeys: ['ebitMargin', 'taxRate', 'capexPct', 'daPct'],
    rowKeys: ['unleveredFcf'],
    previewKey: 'unleveredFcf',
  },
  {
    id: 'wacc',
    pillLabel: 'Discount rate',
    title: 'Cost of equity and WACC',
    instruction: 'CAPM builds cost of equity; WACC blends equity and debt costs.',
    whyOrder: 'You need a discount rate before present-value math means anything.',
    tableRows: 'DCF summary → WACC',
    formula: 'Cost of equity = risk-free + beta × ERP; WACC = weighted average',
    assumptionKeys: ['riskFreeRate', 'equityRiskPremium', 'beta', 'interestRate'],
    rowKeys: [],
    previewKey: 'wacc',
  },
  {
    id: 'terminal',
    pillLabel: 'Terminal value',
    title: 'Terminal value',
    instruction: 'Value cash flows after year five. Terminal growth must stay below WACC.',
    whyOrder: 'Most DCF value often lives in the “forever” tail — make it explicit.',
    tableRows: 'DCF → Terminal value lump sum',
    formula: 'Terminal value = FCF × (1 + g) ÷ (WACC − g)',
    assumptionKeys: ['terminalGrowth'],
    rowKeys: [],
    previewKey: 'terminalValue',
  },
  {
    id: 'discount',
    pillLabel: 'Discount to today',
    title: 'Discount forecast and terminal cash flow',
    instruction: 'Discount each year’s FCF and the terminal lump sum back to today at WACC.',
    whyOrder: 'Future dollars are worth less today — this step converts the forecast to present value.',
    tableRows: 'DCF → Enterprise value',
    formula: 'PV = FCF ÷ (1 + WACC)^year',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'enterpriseValue',
  },
  {
    id: 'bridge',
    pillLabel: 'Share price',
    title: 'Enterprise value to implied share price',
    instruction: 'Subtract debt, add cash, divide by shares outstanding.',
    whyOrder: 'Enterprise value is for the whole company; investors care about per-share price.',
    tableRows: 'DCF summary → Implied share price',
    formula: 'Equity value = EV − debt + cash; price = equity ÷ shares',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'impliedPrice',
  },
];

export const COMPS_STEPS = [
  {
    id: 'peers',
    pillLabel: 'Pick peers',
    title: 'Choose appropriate peers',
    instruction: 'Pick companies that do similar work. Comps are only as honest as this list.',
    whyOrder: 'You cannot compute a market multiple until you decide who is comparable.',
    tableRows: 'Comps table → Peer list',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'peerCount',
  },
  {
    id: 'missing',
    pillLabel: 'Missing data',
    title: 'Inspect missing data',
    instruction: 'Missing multiples stay out of the median — never counted as zero.',
    whyOrder: 'Skipping bad data prevents a false “average” from dragging the answer down.',
    tableRows: 'Comps table → cells marked “nr”',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'missingMultiples',
  },
  {
    id: 'multiples',
    pillLabel: 'Multiples',
    title: 'Review relevant multiples',
    instruction: 'EV/Revenue, EV/EBITDA, and P/E show what the market pays today.',
    whyOrder: 'Multiples translate market prices into ratios you can apply to this company.',
    tableRows: 'Comps table → EV/Revenue, EV/EBITDA, P/E columns',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'evRevenue',
  },
  {
    id: 'stats',
    pillLabel: 'Peer median',
    title: 'Calculate mean and median',
    instruction: 'The middle peer multiple is the usual anchor.',
    whyOrder: 'One outlier peer should not dominate the implied value.',
    tableRows: 'Comps table → Peer median row',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'medianMultiple',
  },
  {
    id: 'apply',
    pillLabel: 'Apply multiple',
    title: 'Apply selected multiples',
    instruction: 'Multiply this company’s metric by the peer median for an implied value.',
    whyOrder: 'This is the payoff — market pricing applied to your company’s metrics.',
    tableRows: 'Implied values table → Implied share price',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'impliedCompsPrice',
  },
  {
    id: 'compare-dcf',
    pillLabel: 'Compare to DCF',
    title: 'Compare implied values with DCF',
    instruction: 'Comps = what buyers pay today; DCF = value of future cash. Both can differ.',
    whyOrder: 'Sanity-check one valuation method against the other.',
    tableRows: 'DCF implied price vs comps implied price',
    assumptionKeys: [],
    rowKeys: [],
    previewKey: 'dcfVsComps',
  },
];

export function stepsForTab(tabId) {
  if (tabId === 'three') return THREE_STATEMENT_STEPS;
  if (tabId === 'dcf') return DCF_STEPS;
  if (tabId === 'comps') return COMPS_STEPS;
  return [];
}
