/**
 * The guesses, in plain English. One entry per editable driver: what it is,
 * where its default came from, and what moving it does.
 *
 * Browser-safe ESM with no imports. The page renders these as cards and the
 * workbook prints the same two sentences next to the same cell, so the
 * spreadsheet and the screen never explain a number differently.
 */

export const DIAL_GROUPS = [
  { id: 'growth', label: 'The business', models: ['three'] },
  { id: 'capital', label: 'Cash and capital', models: ['three'] },
  { id: 'dcf', label: 'What it’s worth', models: ['dcf'] },
];

/**
 * `fmt` is how the value is shown and typed: 'pct' for a percentage, 'days'
 * for a day count, 'num' for a plain multiple.
 */
export const DIALS = [
  {
    key: 'revenueGrowth',
    group: 'growth',
    name: 'Sales growth',
    fmt: 'pct',
    min: -0.2,
    max: 0.4,
    step: 0.005,
    what: 'How much bigger the company gets each year.',
    originKey: 'revenue_yoy',
    originText: (o) => (o == null ? 'Nothing to copy from the filing, so this starts at 4%.' : `Last year sales moved ${o}.`),
    effect: 'Every line on all three statements starts from this number.',
  },
  {
    key: 'grossMargin',
    group: 'growth',
    name: 'Gross margin',
    fmt: 'pct',
    min: 0,
    max: 0.95,
    step: 0.005,
    what: 'Of every sales dollar, what’s left after making the thing you sold.',
    originKey: 'gross_margin',
    originText: (o) => (o == null ? 'This filer doesn’t tag gross profit — banks and insurers usually don’t. The model skips the line rather than invent it.' : `The 10-K kept ${o} of each sales dollar.`),
    effect: 'Sets cost of sales, and inventory is sized off it.',
  },
  {
    key: 'ebitMargin',
    group: 'growth',
    name: 'Operating margin',
    fmt: 'pct',
    min: -0.2,
    max: 0.7,
    step: 0.005,
    what: 'Profit after running the business, before interest and tax.',
    originKey: 'operating_margin',
    originText: (o) => (o == null ? 'Operating income isn’t tagged, so this is backed out of net income and the tax rate.' : `The 10-K reported ${o}.`),
    effect: 'This is the single biggest lever on the DCF.',
  },
  {
    key: 'taxRate',
    group: 'growth',
    name: 'Tax rate',
    fmt: 'pct',
    min: 0,
    max: 0.45,
    step: 0.005,
    what: 'The share of pre-tax profit that goes to governments.',
    originText: () => 'Starts at the 21% US federal statutory rate.',
    effect: 'Lowers net income and the after-tax cash the DCF discounts.',
  },
  {
    key: 'capexPct',
    group: 'capital',
    name: 'Capital spending',
    fmt: 'pct',
    min: 0,
    max: 0.4,
    step: 0.005,
    what: 'Money spent on factories, servers, stores — as a share of sales.',
    originKey: 'capex_intensity',
    originText: (o) => (o == null ? 'CapEx isn’t tagged here, so this starts at 4% of sales.' : `The 10-K spent ${o} of sales.`),
    effect: 'Cash out today, a bigger asset base tomorrow.',
  },
  {
    key: 'daPct',
    group: 'capital',
    name: 'Depreciation',
    fmt: 'pct',
    min: 0,
    max: 0.4,
    step: 0.005,
    what: 'The accounting cost of assets wearing out. No cash leaves the building.',
    originText: () => 'Not a tag in this snapshot, so it starts equal to capital spending — what a steady company roughly replaces each year.',
    effect: 'Cuts profit but is added straight back in the cash flow statement.',
  },
  {
    key: 'dsoDays',
    group: 'capital',
    name: 'Days to get paid',
    fmt: 'days',
    min: 0,
    max: 180,
    step: 1,
    what: 'How long customers take to pay. Longer means cash sits in receivables.',
    originText: (o) => (o == null ? 'Receivables aren’t tagged, so this stays flat instead of guessing.' : `The 10-K implies ${o}.`),
    effect: 'Raising it eats cash without touching profit.',
  },
  {
    key: 'dioDays',
    group: 'capital',
    name: 'Days of inventory',
    fmt: 'days',
    min: 0,
    max: 240,
    step: 1,
    what: 'How long stock sits on shelves before it sells.',
    originText: (o) => (o == null ? 'No inventory tag — a services or financial company usually has none.' : `The 10-K implies ${o}.`),
    effect: 'Same as above: more days, less cash.',
  },
  {
    key: 'interestRate',
    group: 'capital',
    name: 'Interest on debt',
    fmt: 'pct',
    min: 0,
    max: 0.15,
    step: 0.0025,
    what: 'What the company pays to borrow.',
    originText: () => 'Starts at 5%, a rough investment-grade coupon. It’s charged on the balance at the *start* of the year, which is what keeps this model free of circular references.',
    effect: 'Also becomes the cost of debt inside WACC.',
  },
  {
    key: 'debtRepaymentPct',
    group: 'capital',
    name: 'Debt paid down',
    fmt: 'pct',
    min: 0,
    max: 0.5,
    step: 0.01,
    what: 'Share of the loan balance repaid each year.',
    originText: () => 'Starts at 5% if they carry debt, 0% if they don’t.',
    effect: 'Uses cash now, cuts interest later.',
  },
  {
    key: 'payoutRatio',
    group: 'capital',
    name: 'Dividend payout',
    fmt: 'pct',
    min: 0,
    max: 1,
    step: 0.05,
    what: 'Share of profit handed to shareholders instead of kept.',
    originText: () => 'Dividends aren’t in the snapshot, so this starts at zero — every dollar of profit stays in equity until you say otherwise.',
    effect: 'Lowers cash and equity by the same amount, so the sheet still balances.',
  },
  {
    key: 'beta',
    group: 'dcf',
    name: 'Beta',
    fmt: 'num',
    min: 0.2,
    max: 2.5,
    step: 0.05,
    what: 'How violently the stock moves versus the market. 1.0 means it moves with it.',
    originText: () => 'Starts at 1.0 — the market itself.',
    effect: 'Higher beta means a higher discount rate and a lower value.',
  },
  {
    key: 'riskFreeRate',
    group: 'dcf',
    name: 'Risk-free rate',
    fmt: 'pct',
    min: 0,
    max: 0.1,
    step: 0.0025,
    what: 'What you’d earn lending to the US government instead.',
    originText: () => 'Starts near the recent 10-year Treasury yield.',
    effect: 'The floor under every other return in the model.',
  },
  {
    key: 'equityRiskPremium',
    group: 'dcf',
    name: 'Equity risk premium',
    fmt: 'pct',
    min: 0,
    max: 0.12,
    step: 0.0025,
    what: 'The extra return investors demand for owning stocks instead of bonds.',
    originText: () => 'Starts at 5%, the usual textbook figure.',
    effect: 'Multiplied by beta to get the cost of equity.',
  },
  {
    key: 'terminalGrowth',
    group: 'dcf',
    name: 'Growth forever after',
    fmt: 'pct',
    min: 0,
    max: 0.05,
    step: 0.0025,
    what: 'How fast the company grows after the five forecast years — forever.',
    originText: () => 'Starts at 2.5%, roughly long-run inflation. Above the economy’s growth rate and you’ve claimed the company eventually eats the world.',
    effect: 'Usually decides most of the valuation, which is why the sensitivity table exists.',
  },
];

export function dialsFor(models) {
  const active = new Set(DIAL_GROUPS.filter((g) => g.models.some((m) => models.includes(m))).map((g) => g.id));
  return DIALS.filter((d) => active.has(d.group));
}
