/**
 * Worked ASC 606 scenarios. Each one is the same tree with a known path.
 */

export const QUIZZES = [
  {
    id: 'saas',
    title: 'SaaS plus a one-time implementation',
    industry: 'Software',
    story:
      'You sell a 12-month hosted product for $120,000, billed monthly, plus a $30,000 implementation that configures the customer’s instance. They can use the software without you, and you sell implementations separately. Collectibility is fine. No returns, no extra discount, no other party in the middle.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'transfer',
      's2-shipping': 'na',
      's2-warranty': 'none',
      's2-option': 'none',
      's2-principal': 'alone',
      's2-capable': 'yes',
      's2-separable': 'yes',
      's2-series': 'yes',
      's3-variable': 'no',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'observable',
      's4-discount': 'spread',
      's4-var-alloc': 'spread',
      's5-overtime-a': 'yes',
      's5-progress': 'output',
      's5-license': 'none',
    },
    takeaway:
      'Two performance obligations if implementation is distinct: a point-in-time or short over-time implementation (whatever control says) and a series of hosted access recognized over the year. Allocate $150,000 on relative standalone selling prices — do not dump the implementation fee into day-one revenue just because that is how it was invoiced.',
  },
  {
    id: 'custom-build',
    title: 'Custom warehouse on the customer’s land',
    industry: 'Construction',
    story:
      'A developer hires you to build a warehouse on land they already own. The building is specified to their site. If they cancel for convenience, the contract and local law entitle you to payment for performance to date, including a reasonable margin. They pay monthly. No other Topic applies.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'none',
      's2-shipping': 'na',
      's2-warranty': 'assurance',
      's2-option': 'none',
      's2-principal': 'alone',
      's2-capable': 'no',
      's2-series': 'no',
      's3-variable': 'no',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'single',
      's5-overtime-a': 'no',
      's5-overtime-b': 'yes',
      's5-progress': 'input',
      's5-license': 'none',
    },
    takeaway:
      'One performance obligation (the building is not a pile of distinct bricks). Over time under 25-27(b) because they control the WIP on their land — and 25-27(c) would also often be true. Recognize as you measure progress, typically cost-to-cost, not when they get the keys.',
  },
  {
    id: 'marketplace',
    title: 'Marketplace that never touches the goods',
    industry: 'Platform',
    story:
      'Your site lets independent sellers list furniture. The buyer pays you $1,000; you keep a $150 fee and pass $850 to the seller. You never take title or inventory risk. The seller is primarily responsible for the furniture and sets the price. You are just the checkout rail.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'none',
      's2-shipping': 'na',
      's2-warranty': 'none',
      's2-option': 'none',
      's2-principal': 'agent',
      's2-capable': 'yes',
      's2-separable': 'yes',
      's2-series': 'no',
      's3-variable': 'no',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'single',
      's5-overtime-a': 'yes',
      's5-progress': 'output',
      's5-license': 'none',
    },
    takeaway:
      'You are an agent for the furniture. Transaction price is the $150 fee, not $1,000. The $850 you pass through is not your revenue. Recognize the fee when you satisfy the arranging service — usually when the sale is completed.',
  },
  {
    id: 'returns',
    title: 'Retailer with a 30-day return right',
    industry: 'Retail',
    story:
      'A store sells a $80 sweater. Customers may return it for 30 days, no questions. History says 8% come back. You can resell returns. The customer paid cash at the register. You are the principal. Shipping is before they take the bag.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'none',
      's2-shipping': 'na',
      's2-warranty': 'assurance',
      's2-option': 'none',
      's2-principal': 'principal',
      's2-capable': 'yes',
      's2-separable': 'yes',
      's2-series': 'no',
      's3-variable': 'yes',
      's3-method': 'expected',
      's3-constraint': 'full',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'single',
      's5-overtime-a': 'no',
      's5-overtime-b': 'no',
      's5-overtime-c-alt': 'yes',
      's5-point': 'continue',
      's5-license': 'none',
    },
    takeaway:
      'The return right makes consideration variable. Expected value on a portfolio of similar sales is the usual estimate. Recognize $73.60 of revenue (if 8% is the expected return), a refund liability, and an asset for the right to recover the sweater. Not $80 with a later surprise.',
  },
  {
    id: 'collectibility',
    title: 'Customer who probably will not pay',
    industry: 'Credit',
    story:
      'You sign a one-year service contract with a new customer whose business is already missing payroll. They paid a $5,000 nonrefundable deposit. You do not believe it is probable you will collect substantially all of the remaining $55,000, even after any concession you would realistically give.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'no',
      's1-fail': 'cash',
    },
    takeaway:
      'Step 1 dies on collectibility. The $5,000 is a liability, not revenue, until a 25-7 event (you are done and the cash is nonrefundable, the contract is terminated and the cash is nonrefundable, or you have transferred control of what that cash relates to, stopped, and have no further obligation). Keep reassessing if facts change.',
  },
  {
    id: 'brand-license',
    title: 'Brand license with a sales royalty',
    industry: 'IP',
    story:
      'You license a well-known brand name to a manufacturer for three years. They pay a 6% royalty on their sales of branded product. You will keep advertising and developing the brand, and they are exposed to those activities. The license is the only promise. Collectibility of royalties as they arise is fine.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'none',
      's2-shipping': 'na',
      's2-warranty': 'none',
      's2-option': 'none',
      's2-principal': 'alone',
      's2-capable': 'yes',
      's2-separable': 'yes',
      's2-series': 'no',
      's3-variable': 'yes',
      's3-method': 'expected',
      's3-constraint': 'royalty',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'single',
      's5-overtime-a': 'yes',
      's5-progress': 'output',
      's5-license': 'access',
    },
    takeaway:
      'Symbolic brand licenses are typically a right to access (over time). The 6% is a sales-based royalty for a license of IP, so the royalty exception wins: recognize when the later of the underlying sale and satisfaction of the license occurs — in practice, as they sell.',
  },
  {
    id: 'gift-card',
    title: 'Gift card that is a material right',
    industry: 'Retail',
    story:
      'A coffee chain sells a $50 gift card. The card is not a product; it is an option to buy future drinks. Customers do not get that stored value without buying the card. You expect some cards never to be used, but you cannot yet book that breakage as cash sitting in the till.',
    answers: {
      start: 'begin',
      'scope-customer': 'yes',
      'scope-kind': 'in',
      's1-form': 'yes',
      's1-approved': 'yes',
      's1-rights': 'yes',
      's1-payment': 'yes',
      's1-substance': 'yes',
      's1-collect': 'yes',
      's1-combine': 'no',
      's1-mod': 'no',
      's2-promises': 'continue',
      's2-setup': 'none',
      's2-shipping': 'na',
      's2-warranty': 'none',
      's2-option': 'yes',
      's2-principal': 'principal',
      's2-capable': 'yes',
      's2-separable': 'yes',
      's2-series': 'no',
      's3-variable': 'no',
      's3-finance': 'no',
      's3-noncash': 'no',
      's3-payable': 'no',
      's4-ssp': 'single',
      's5-overtime-a': 'no',
      's5-overtime-b': 'no',
      's5-overtime-c-alt': 'yes',
      's5-point': 'continue',
      's5-license': 'none',
    },
    takeaway:
      'The card is a material right: the customer paid in advance for future goods. Cash is a contract liability. Revenue waits until drinks are transferred or the option expires (including breakage you can reasonably estimate). Paying in advance with the customer choosing the date is also why this is not a significant financing component.',
  },
];

export function quizById(id) {
  return QUIZZES.find((q) => q.id === id) || null;
}
